<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYBOxDtx\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYBOxDtx/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerYBOxDtx.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerYBOxDtx\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerYBOxDtx\App_KernelProdContainer([
    'container.build_hash' => 'YBOxDtx',
    'container.build_id' => 'd455759b',
    'container.build_time' => 1747759489,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYBOxDtx');
