nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:4200', 'http://infla.cat:43000']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    paths:
        '^/': ~
