<?php

namespace ContainerYBOxDtx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ba3_KOOService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.ba3.KOO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ba3.KOO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'exchangeRepository' => ['privates', 'App\\Repository\\ExchangeRepository', 'getExchangeRepositoryService', true],
        ], [
            'entityManager' => '?',
            'exchangeRepository' => 'App\\Repository\\ExchangeRepository',
        ]);
    }
}
