<?php

namespace ContainerYBOxDtx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExchangeRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ExchangeRepository' shared autowired service.
     *
     * @return \App\Repository\ExchangeRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ExchangeRepository'] = new \App\Repository\ExchangeRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
