<?php

namespace ContainerYBOxDtx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImagesControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ImagesController' shared autowired service.
     *
     * @return \App\Controller\ImagesController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ImagesController'] = $instance = new \App\Controller\ImagesController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\ItemRepository'] ?? $container->load('getItemRepositoryService')), ($container->privates['App\\Service\\FileUploader'] ??= new \App\Service\FileUploader((\dirname(__DIR__, 4).'/public/uploads'))));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\ImagesController', $container));

        return $instance;
    }
}
