<?php

namespace ContainerYBOxDtx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItemRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ItemRepository' shared autowired service.
     *
     * @return \App\Repository\ItemRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ItemRepository'] = new \App\Repository\ItemRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
