<?php

namespace ContainerYBOxDtx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItem2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.yb1ro4H.App\Entity\Item' shared service.
     *
     * @return \App\Entity\Item
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.yb1ro4H": it needs an instance of "App\\Entity\\Item" but this type has been excluded in "config/services.yaml".');
    }
}
