<?php

namespace ContainerYBOxDtx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationControllergetNotificationsService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.IZrDbAW.App\Controller\NotificationController::getNotifications()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IZrDbAW.App\\Controller\\NotificationController::getNotifications()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'notificationRepository' => ['privates', 'App\\Repository\\NotificationRepository', 'getNotificationRepositoryService', true],
        ], [
            'notificationRepository' => 'App\\Repository\\NotificationRepository',
        ]))->withContext('App\\Controller\\NotificationController::getNotifications()', $container);
    }
}
