apiVersion: v1
kind: Service
metadata:
  name: angular-frontend-service
  namespace: grup9
spec:
  selector:
    app: angular-frontend
  ports:
    - port: 80        
      targetPort: 80
  type: ClusterIP
