apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
  namespace: grup9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: images-volume
          mountPath: /var/www/html/public/uploads
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: images-volume
        persistentVolumeClaim:
          claimName: images-pvc
