apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: grup9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "1qazZAQ!"
            - name: MYSQL_DATABASE
              value: "project"
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "1qazZAQ!"
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
