apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: grup9
data:
  nginx.conf: |
    worker_processes  1;

    events {
        worker_connections  1024;
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;
        sendfile      on;
        keepalive_timeout  65;

        server {
            listen 80;
            server_name kube0.lacetania.cat;

            root /var/www/html/public;
            index index.php index.html;

            location /api/ {
                try_files $uri /index.php$is_args$args;
            }

            location ~ ^/index\.php(/|$) {
                fastcgi_pass symfony-service:9000;
                fastcgi_split_path_info ^(.+\.php)(/.*)$;
                fastcgi_param SCRIPT_FILENAME $document_root/index.php;
                fastcgi_param PATH_INFO $fastcgi_path_info;
                include fastcgi_params;
                fastcgi_read_timeout 3600s;
            }

            location /images/ {
                try_files $uri $uri/ =404;
            }

            location /uploads/ {
                alias /var/www/html/public/uploads/;
                try_files $uri =404;
            }


            location / {
                proxy_pass http://angular-frontend-service:80;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_read_timeout 3600s;
                proxy_send_timeout 3600s;
            }
        }
    }
