<?php

namespace ContainerDr0Ftf1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExchangeControllerrejectExchangeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ba3.KOO.App\Controller\ExchangeController::rejectExchange()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ba3.KOO.App\\Controller\\ExchangeController::rejectExchange()'] = ($container->privates['.service_locator.ba3.KOO'] ?? $container->load('get_ServiceLocator_Ba3_KOOService'))->withContext('App\\Controller\\ExchangeController::rejectExchange()', $container);
    }
}
