<?php

namespace ContainerDr0Ftf1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItemControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yb1ro4H.App\Controller\ItemController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yb1ro4H.App\\Controller\\ItemController::delete()'] = ($container->privates['.service_locator.yb1ro4H'] ?? $container->load('get_ServiceLocator_Yb1ro4HService'))->withContext('App\\Controller\\ItemController::delete()', $container);
    }
}
