<?php

namespace ContainerDr0Ftf1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItemControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ItemController' shared autowired service.
     *
     * @return \App\Controller\ItemController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ItemController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/FileUploader.php';

        $container->services['App\\Controller\\ItemController'] = $instance = new \App\Controller\ItemController(($container->privates['App\\Service\\FileUploader'] ??= new \App\Service\FileUploader((\dirname(__DIR__, 4).'/public/uploads'))), ($container->services['App\\Controller\\ImagesController'] ?? $container->load('getImagesControllerService')), ($container->privates['validator'] ?? self::getValidatorService($container)));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\ItemController', $container));

        return $instance;
    }
}
